"""Start DB

Revision ID: f16eed6ead4e
Revises: 
Create Date: 2023-11-30 11:30:58.878229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f16eed6ead4e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drivers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("auth", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code_item", sa.String(length=11), nullable=False),
        sa.Column("unit", sa.String(length=5), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("quantity_shipped", sa.Float(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("sum", sa.Float(), nullable=False),
        sa.Column("discount", sa.Float(), nullable=False),
        sa.Column("bonus", sa.Float(), nullable=False),
        sa.Column("order_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_items_code_item"), "items", ["code_item"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("orde_1c_number", sa.String(length=11), nullable=False),
        sa.Column("id_search", sa.Integer(), nullable=False),
        sa.Column("buyer", sa.String(length=250), nullable=False),
        sa.Column("telephone", sa.String(length=12), nullable=False),
        sa.Column("address", sa.TEXT(), nullable=False),
        sa.Column("comment", sa.TEXT(), nullable=True),
        sa.Column("driver_id", sa.Integer(), nullable=False),
        sa.Column("delivered", sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    op.drop_index(op.f("ix_items_code_item"), table_name="items")
    op.drop_table("items")
    op.drop_table("drivers")
    # ### end Alembic commands ###
